name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]

    runs-on: ${{ matrix.os }}
    environment: ${{ github.event_name == 'push' && 'Production' || 'Preview' }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Install Dependencies
        run: |
          npm i -g corepack
          corepack enable
          pnpm install

      - name: Build and Test
        run: pnpm test
